---
authors:
  - Jakob Meng (https://github.com/jm1)
dependencies: {}
description: null
documentation: https://github.com/jm1/ansible-collection-libvirt/tree/master/docs
homepage: https://github.com/jm1/ansible-collection-libvirt
issues: https://github.com/jm1/ansible-collection-libvirt/issues
license: GPL-3.0-or-later
license_file: LICENSE.md
name: libvirt
namespace: jm1
readme: README.md
repository: https://github.com/jm1/ansible-collection-libvirt
tags: null
version: 2020.06.12
