---
- name: Load tasks specific to OS
  include_tasks: "setup-{{ ansible_facts['distribution'] }}.yml"
  when: ansible_facts['distribution'] in [ 'CentOS', 'Debian', 'Red Hat Enterprise Linux', 'Ubuntu' ]
