---
# Copyright (c) 2021-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# NOTE: Synchronize changes with chapter Requirements in README.md

# NOTE: Variables are sorted by name

configdrive: '{{ inventory_hostname }}_cidata.{{ configdrive_format }}'

configdrive_filesystem: 'iso'

configdrive_format: 'raw'

# Variable distribution_id is a list which uniquely identifies a distribution release, e.g.
#  ['CentOS', '8'] for CentOS 8 (both Core and Stream)
#  ['Debian', '10'] for Debian 10 (Buster)
#  ['Red Hat Enterprise Linux', '8' ]` for Red Hat Enterprise Linux (RHEL) 8
#  ['Ubuntu', '20.04' ] for Ubuntu 20.04 LTS (Focal Fossa)
#
# NOTE: Version numbers for upcoming Debian releases are not stable. For example, when lsb_release is available, which
# is the default, Ansible will report 'n/a' for Debian's testing and unstable (Sid) distributions. When lsb_release
# has been uninstalled, the version string will be 'trixie/sid' or similar. In the past, 'NA' would be reported when
# lsb_release was not available and 'testing' or 'sid' when it was installed.
distribution_id:
- '{{ ansible_facts.distribution }}'
- # Use major and minor version for Ubuntu, e.g. Ubuntu 18.04 LTS (Bionic Beaver) or Ubuntu 20.04 LTS (Focal Fossa).
  # Use major version for all other distributions, e.g. CentOS 7, Debian 10 (Buster) or Red Hat Enterprise Linux 8.
  "{{ ansible_facts.distribution_version if ansible_facts.distribution == 'Ubuntu' else
      ansible_facts.distribution_major_version }}"

domain: '{{ inventory_hostname }}'

hardware:
- cpu: 'host'
- vcpus: '2'
- memory: '1024'
- virt_type: 'kvm'
- graphics: 'spice,listen=socket'
# With --network being omitted a single NIC will be created in the guest.
# Ref.: man virt-install
#
# - network: 'network=default,model=virtio'
- disk: "vol='{{ pool }}/{{ volume }}',device=disk,bus=virtio,serial='root'"
- disk: "vol='{{ pool }}/{{ configdrive }}',device=disk,bus=virtio,serial='cidata'"
# Specifying os variant is HIGHLY RECOMMENDED, as it can greatly increase performance by specifying virtio
# among other guest tweaks. It also enables support for QEMU Guest Agent by adding a virtio-serial channel.
# Ref.: man virt-install
- os_variant: 'linux2020'

image: "{{ image_uri | urlsplit('path') | basename }}"

image_checksum: |-
    {{
    {
        'CentOS 7': 'sha256:1db30c9c272fb37b00111b93dcebff16c278384755bdbe158559e9c240b73b80',
        'CentOS 8': omit,
        'CentOS 9': omit,
        'Debian 10': omit,
        'Debian 11': omit,
        'Debian 12': omit,
        'Debian 13': omit,
        'Ubuntu 20.04': omit,
        'Ubuntu 22.04': omit,
        'Ubuntu 24.04': omit
    }[distribution_id | join(' ')]
    }}

image_format: |-
    {{
    {
        'Ubuntu 20.04': 'qcow2',
        'Ubuntu 22.04': 'qcow2',
        'Ubuntu 24.04': 'qcow2'
    }[distribution_id | join(' ')] | default((image | splitext | last)[1:])
    }}

# TODO: Replace daily image with latest stable image when Debian 13 (Trixie) has been released.
image_uri: |-
    {{
    {
        'CentOS 7': 'https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2003.qcow2',
        'CentOS 8': 'https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-latest.x86_64.qcow2',
        'CentOS 9': 'https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2',
        'Debian 10': 'https://cdimage.debian.org/images/cloud/buster/latest/debian-10-genericcloud-amd64.qcow2',
        'Debian 11': 'https://cdimage.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2',
        'Debian 12': 'https://cdimage.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2',
        'Debian 13': 'https://cdimage.debian.org/images/cloud/trixie/daily/latest/debian-13-genericcloud-amd64-daily.qcow2',
        'Ubuntu 20.04': 'https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img',
        'Ubuntu 22.04': 'https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img',
        'Ubuntu 24.04': 'https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img'
    }[distribution_id | join(' ')]
    }}

metadata: !!null

networkconfig: !!null

pool: 'default'

prealloc_metadata: false

state: present

uri: 'qemu:///system'

userdata: |
    #cloud-config

volume: "{{ inventory_hostname }}.{{ volume_format }}"

volume_capacity: |-
    {{
    {
        'CentOS 7': '5G',
        'Debian 10': '5G',
        'Ubuntu 18.04': '5G'
    }[distribution_id | join(' ')] | default('10G')
    }}

volume_cow: false

volume_format: 'qcow2'
