---
# NOTE: Synchronize changes with chapter Requirements in README.md

# NOTE: Variables are sorted by name

__configdrive: '{{ inventory_hostname }}_[cidata].{{ configdrive_format }}'

__configdrive_filesystem: 'iso'

__configdrive_format: 'raw'

__domain: '{{ inventory_hostname }}'

__hardware: !!null

__image: '{{image_uri|urlsplit("path")|basename}}'

__image_checksum: 'sha256:37f24aab47b9692e24f8f4dd7f8fcd86214e1a7feef23f744e1f06c377f43b13'

__image_format: 'qcow2'

__image_uri: 'https://cloud-images.ubuntu.com/focal/20200616/focal-server-cloudimg-amd64.img'

__metadata: !!null

__networkconfig: !!null

__pool: 'default'

__pool_hardware:
- type: dir
- target: '/var/lib/libvirt/images'

__prealloc_metadata: no

__state: present

__uri: 'qemu:///system'

__userdata: |
    #cloud-config

__volume: '{{ inventory_hostname }}.{{ volume_format }}'

__volume_capacity: '10G'

__volume_cow: no

__volume_format: 'qcow2'
