---
# Copyright (c) 2020-2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# NOTE: Synchronize changes with README.md

# Tasks for Debian and Ubuntu have been unified in a single file because of similarities between both distributions.

# No need to update apt cache here because role jm1.pkg.setup handles apt cache updates already

- name: Satisfy requirements for collection jm1.libvirt on Debian 10 (Buster) and Ubuntu 18.04 LTS (Bionic Beaver)
  jm1.pkg.meta_pkg:
    name: "jm1-libvirt-setup"
    version: "1"
    depends:
    - jm1-pkg-setup
    - cloud-image-utils
    - libvirt-clients
    - python-backports.tempfile
    - python-libvirt
    - python-lxml
    - python3-libvirt
    - python3-lxml
    - virtinst
