---
# Copyright (c) 2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# NOTE: Synchronize changes with README.md

- name: Install package dependencies for Fedora
  jm1.pkg.meta_pkg:
    name: "jm1-libvirt-setup"
    version: "1"
    depends:
    - jm1-pkg-setup
    - cloud-utils
    - python3-libvirt
    - python3-lxml
    - libvirt-client
    - virt-install
