---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# NOTE: Synchronize changes with README.md

- name: Enable yum repositories for Extra Packages for Enterprise Linux (EPEL)
  import_role:
    name: jm1.pkg.yum_repository
  vars:
    yum_repository_config: '{{ yum_repository_config_epel }}'

- name: Satisfy requirements for collection jm1.libvirt on Red Hat Enterprise Linux 7 and CentOS 7
  when: distribution_id|last == '7'
  block:
  - name: Install package dependencies for Red Hat Enterprise Linux 7 and CentOS 7
    jm1.pkg.meta_pkg:
      name: "jm1-libvirt-setup"
      version: "1"
      depends:
      - jm1-pkg-setup
      - cloud-utils
      - python-backports
      - python-pip
      - python-lxml
      - libvirt-client
      - libvirt-python
      - virt-install

  - name: Install pip dependencies for Red Hat Enterprise Linux 7 and CentOS 7
    block:
    - pip:
        name: backports.tempfile

- name: Satisfy requirements for collection jm1.libvirt on Red Hat Enterprise Linux 8 and 9 and CentOS 8 and 9
  when: distribution_id|last in ['8', '9']
  block:
  - name: Install package dependencies for Red Hat Enterprise Linux 8 and 9 and CentOS 8 and 9
    jm1.pkg.meta_pkg:
      name: "jm1-libvirt-setup"
      version: "1"
      depends:
      - jm1-pkg-setup
      - python3-libvirt
      - python3-lxml
      - libvirt-client
      - virt-install
