---
# NOTE: Synchronize changes with README.md

# Tasks for Debian and Ubuntu have been unified in a single file because of similarities between both distributions.

# No need to update apt cache here because role jm1.pkg.setup handles apt cache updates already

- name: Satisfy requirements for collection jm1.libvirt on Debian 10 (Buster) and Ubuntu 18.04 LTS (Bionic Beaver)
  when: distribution_id in [['Debian', '10'], ['Ubuntu', '18.04']]
  jm1.pkg.meta_pkg:
    name: "jm1-libvirt-setup"
    version: "1"
    depends:
    - jm1-pkg-setup
    - cloud-image-utils
    - libvirt-clients
    - python-backports.tempfile
    - python-libvirt
    - python-lxml
    - python3-libvirt
    - python3-lxml
    - virtinst

- name: >-
    Satisfy requirements for collection jm1.libvirt on Debian 11 (Bullseye), Debian NA (Testing, Unstable aka Sid,
    Experimental) and Ubuntu 20.04 LTS (Focal Fossa)
  when: distribution_id in [
            ['Debian', '11'],
            ['Debian', 'NA'],
            ['Debian', 'Testing'],
            ['Debian', 'Unstable'],
            ['Ubuntu', '20.04']
        ]
  jm1.pkg.meta_pkg:
    name: "jm1-libvirt-setup"
    version: "1"
    depends:
    - jm1-pkg-setup
    - cloud-image-utils
    - libvirt-clients
    - python3-libvirt
    - python3-lxml
    - virtinst
